#!/bin/zsh

ssh_host=${$(pstree -al $1  | grep "\-ssh" | sed 's/[\t ]\+/\t/g' | cut -f 4)%%.*}

if git_status=$(cd $2 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
  case $git_status in
    *Changes\ not\ staged* ) state="#[bg=colour013,fg=black] ± #[fg=default]" ;;
    *Changes\ to\ be\ committed* ) state="#[bg=blue,fg=black] + #[default]" ;; 
    * ) state="#[bg=green,fg=black] ✔ #[default]" ;;
  esac
  if [[ $git_branch = "master" ]]; then
    git_info="#[underscore]#[bg=black,fg=blue] ⭠ ${git_branch} #[default]${state}"
  else
    git_info="#[underscore]#[bg=black,fg=colour014] ⭠ ${git_branch} #[default]${state}"
  fi
else
  git_info=""
fi

directory="$2"

if [ ! -z $ssh_host ]; then
    echo "$ssh_host"
else
    echo "${HOST%%.*}:$directory$git_info"
fi

